DROP TABLE IF EXISTS CAR_ENTITY;
  
CREATE TABLE CAR_ENTITY (
  ID IDENTITY NOT NULL PRIMARY KEY, 
  VIN VARCHAR(17) NOT NULL,
  MAKE VARCHAR(max) NOT NULL,
  MODEL VARCHAR(max) NOT NULL,
  PLATE_NUMBER VARCHAR(max),
  UNIQUE KEY CAR_ENTITY_VIN_UNIQUE (vin)
);

DROP TABLE IF EXISTS CAR_LOCK;
  
CREATE TABLE CAR_LOCK (
  ID IDENTITY NOT NULL PRIMARY KEY, 
  VIN VARCHAR(17) NOT NULL,
  KEY_LOCK VARCHAR(36),
  UNIQUE KEY CAR_LOCK_VIN_UNIQUE (vin)
);
